name: arkit_plugin_example
description: Demonstrates how to use the arkit_plugin plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies to shared and manage cloud anchor IDs and related content
  firebase_core: "^1.6.0"
  cloud_firestore: "^2.5.3"
  geoflutterfire: "^3.0.1"
  path_provider: "^2.0.3"
  flutter_archive: "^4.0.1"
  arkit_plugin:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1

  arkit_plugin:
    path: ../

flutter:
  uses-material-design: true